# frozen_string_literal: true

class RadioErrors
  ERROR_CONNECTION = -1
  SUCCESS = 0
  INVALID_INPUT = 1
  INVALID_COMMAND = 2
  INVALID_RADIO_MODEL = 3
  INVALID_SERIAL_LENGTH = 4
  INVALID_SERIAL_PATTERN = 5
  INVALID_SERIAL_NOT_SUPPORTED = 6
  INVALID_EXTRA_LENGTH = 7
  INVALID_EXTRA_PATTERN = 8
  INVALID_LICENSE = 100
end
